# Generated by Django 5.2.6 on 2025-09-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user_id',
            new_name='user',
        ),
    ]
