# Generated by Django 5.2.6 on 2025-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_alter_table_end_time_alter_table_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(),
        ),
    ]
