# Generated by Django 5.2.6 on 2025-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
