# Generated by Django 5.2.6 on 2025-09-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_user_must_change_password_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
    ]
