# Generated by Django 5.2.6 on 2025-09-22 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_remove_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +9989XXXXXXXX formatida bo‘lishi kerak', regex='^\\+9989\\d{8}$')]),
        ),
    ]
